#
# movingframes3dplotter.py
#
"""
Plot the solution generated by invpolsolver.py
"""

from __future__ import unicode_literals
from numpy import loadtxt
from pylab import figure, plot, xlabel, ylabel, grid, hold, legend, title, savefig
from matplotlib.font_manager import FontProperties
import matplotlib as mpl
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

mpl.rcParams['text.usetex']=True
mpl.rcParams['text.latex.unicode']=True

xhatphi = loadtxt('data/movingframes.dat')

fig = plt.figure()
ax = fig.gca(projection='3d')

#ax.plot(xhatphi[0:20000,0], xhatphi[0:20000,2], xhatphi[0:20000,3], linewidth=0.3)
ax.plot(xhatphi[:,0], xhatphi[:,2], xhatphi[:,3], linewidth=0.3)
ax.set_xlabel('$\hat{x}_1$', fontsize=16)
ax.set_ylabel('$\hat{x}_2$', fontsize=16)
ax.set_zlabel('$\hat{y}_2$', fontsize=16)
ax.w_xaxis.set_pane_color((1, 1, 1, 1.0))
ax.w_yaxis.set_pane_color((1, 1, 1, 1.0))
ax.w_zaxis.set_pane_color((1, 1, 1, 1.0))
ax.view_init(20,-65)
savefig('image/movingframes.png', bbox_inches='tight', dpi=100)

#fig2 = plt.figure()
#plt.plot(t,phi)

plt.tight_layout()
plt.show()
