#! /bin/bash

dir0=`pwd`
cd $1

find . -type f -name "*.eps" -print | while read i
do
	echo "Processing file" $i
	convert +antialias $i $i.png
	bmeps -leps3 -tpng -a $i.png $i.tmp
	mv $i.png $2
	mv $i.tmp $2/$i
done
