#! /bin/sh
# Found in the web, almost verbatim. The person blamed was
# Jim Dennis <jadestar@rahul.net>.

# First argument is filename. The second is search string
# and the 3rd is replace string. 

find . -type f -name "$3" -print | while read i
do
	grep $1 --with-filename $2  $i 
done

