#! /bin/sh
# Found in the web, almost verbatim. The person blamed was
# Jim Dennis <jadestar@rahul.net>.

# First argument is filename. The second is search string
# and the 3rd is replace string. 

find . -type f -name "$1" -print | while read i
do
	sed "s|$2|$3|g" $i > $i.tmp && mv $i.tmp $i
done

