#
# movingframes3dplotter.py
#
"""
Plot the solution generated by invpolsolver.py
"""

from __future__ import unicode_literals
from numpy import loadtxt
from pylab import figure, plot, xlabel, ylabel, grid, hold, legend, title, savefig
from matplotlib.font_manager import FontProperties
import matplotlib as mpl
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
import matplotlib.pyplot as plt
import numpy as np

mpl.rcParams['text.usetex']=True
mpl.rcParams['text.latex.unicode']=True

t, x1GS, y1GS, y2GS = loadtxt('data/gramschmidt.dat', unpack=True)

fig = plt.figure()
ax = fig.gca(projection='3d')
x = [0,-4,-4,0]
y = [0,0,0,0]
z = [0,0,-2.5,-2.5]
verts = [zip(x, y,z)]
poly = Poly3DCollection(verts, facecolor = 'r', alpha=0.5)
ax.plot(x1GS[0:30000], y1GS[0:30000], y2GS[0:30000], linewidth=0.3)
ax.add_collection3d(poly)

ax.set_xlabel('$\hat{x}_{1,GS}$', fontsize=16)
ax.set_ylabel('$\hat{y}_{1,GS}$', fontsize=16)
ax.set_zlabel('$\hat{y}_{2,GS}$', fontsize=16)
ax.view_init(60,50)
savefig('image/gramschmidtandpsect.png', bbox_inches='tight', dpi=200)

plt.tight_layout()
plt.show()
