#
# movingframes3dplotter.py
#
"""
Plot the solution generated by invpolsolver.py
"""

from __future__ import unicode_literals
from numpy import loadtxt
from pylab import figure, plot, xlabel, ylabel, grid, hold, legend, title, savefig
from matplotlib.font_manager import FontProperties
import matplotlib as mpl
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

mpl.rcParams['text.usetex']=True
mpl.rcParams['text.latex.unicode']=True

t, x1hat, x2hat, y1hat, y2hat, phi = loadtxt('data/movingframes.dat', unpack=True)

fig = plt.figure()
ax = fig.gca(projection='3d')

ax.plot(x1hat, y1hat, y2hat, linewidth=0.3)
ax.set_xlabel('$\hat{x}_1$', fontsize=16)
ax.set_ylabel('$\hat{y}_1$', fontsize=16)
ax.set_zlabel('$\hat{y}_2$', fontsize=16)
#ax.view_init(15,30)
savefig('image/movingframes.png', bbox_inches='tight', dpi=100)

fig2 = plt.figure()
plt.plot(t,phi)

plt.tight_layout()
plt.show()
